site_name: Recipes
site_url: https://recipes.livecchi.cloud
site_author: Joseph Livecchi
extra_css:
  - custom.css
theme:
  name: 'material'
  logo: 'imgs/cake-variant.png'
  favicon: 'imgs/favicon.png'
  features:
    - instant

repo_name: joewashear007/recipes
repo_url: https://bitbucket.org/joewashear007/recipes
edit_uri: src/master/docs/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra:
  manifest: manifest.webmanifest